parameters:
#    vet_cabinet_api.example.class: VetCabinet\ApiBundle\Example

services:
#    vet_cabinet_api.example:
#        class: %vet_cabinet_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
