vet_cabinet_frontend:
    resource: "@VetCabinetFrontendBundle/Resources/config/routing.yml"
    prefix:   /

vet_cabinet_assetic:
    resource: "@VetCabinetAsseticBundle/Resources/config/routing.yml"
    prefix:   /

vet_cabinet_api:
    resource: "@VetCabinetApiBundle/Resources/config/routing.yml"
    prefix:   /

vet_cabinet_core:
    resource: "@VetCabinetCoreBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
