parameters:
#    vet_cabinet_core.example.class: VetCabinet\CoreBundle\Example

services:
  vetcabinet.auth.handler.login_success_handler:
    class: VetCabinet\CoreBundle\Auth\Handler\LoginAuthHandler
    arguments:  [@router, @security.context, @doctrine.orm.entity_manager, @service_container]

  vetcabinet.auth.handler.login_social_success_handler:
    class: VetCabinet\CoreBundle\Auth\Handler\LoginSocialAuthHandler
    arguments:  [@router, @security.context, @doctrine.orm.entity_manager, @service_container]

  vetcabinet.auth.handler.logout_success_handler:
    class:  VetCabinet\CoreBundle\Auth\Handler\LogoutAuthHandler
    arguments:  [@router, @security.context, @service_container]

  vetcabinet.oauth.user.provider:
    class: VetCabinet\CoreBundle\Auth\VetCabinetOAuthUserProvider
    arguments:  [@doctrine.orm.entity_manager, @service_container]

