parameters:
#    vet_cabinet_frontend.example.class: VetCabinet\FrontendBundle\Example

services:
#    vet_cabinet_frontend.example:
#        class: %vet_cabinet_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
