parameters:
#    vet_cabinet_assetic.example.class: VetCabinet\AsseticBundle\Example

services:
#    vet_cabinet_assetic.example:
#        class: %vet_cabinet_assetic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
